name: Common Deployment Workflow

on:
  workflow_call:
    inputs:
      ENV_VAR:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL_FAILED:
        required: true
      SLACK_WEBHOOK_URL_FAILED_2:
        required: true

# common env
env:
  ENV_SLACK_WEBHOOK_URL_FAILED: ${{ secrets.SLACK_WEBHOOK_URL_FAILED }}


jobs:
  github-variable-print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      # github variable 出力
      # github.ref: ワークフローがトリガーされたリファレンスまたはブランチ。プルリクエストの場合、この値はプルリクエストのマージブランチになります（例：refs/pull/:prNumber/merge）。
      # github.ref_name: ワークフローがトリガーされたリファレンスの名前。これはブランチ名またはタグ名になります。
      # github.head_ref: プルリクエストのソースブランチの名前。プルリクエスト以外のイベントではこの値は空です。
      # github.base_ref: プルリクエストのターゲットブランチの名前。プルリクエスト以外のイベントではこの値は空です。
      # github.event_name: イベントの名前。ワークフローがトリガーされたイベントの名前です。例えば、push、pull_request、issuesなどです。
      - name: Print github
        run: |
          echo '1 $GITHUB_REF:'       $GITHUB_REF
          echo '2 github.ref:'        ${{ github.ref }}
          echo '3 github.ref_name:'   ${{ github.ref_name }}
          echo '4 github.head_ref:'   ${{ github.head_ref }}
          echo '5 github.base_ref:'   ${{ github.base_ref }}
          echo '6 github.event_name:' ${{ github.event_name }}

  deploy-to-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Development ENV_VAR
        run: echo ${{ inputs.ENV_VAR }}

      - name: Deploy to Development SLACK_WEBHOOK_URL_FAILED
        run: |
          echo ${{ env.ENV_SLACK_WEBHOOK_URL_FAILED }}
          echo ${{ secrets.SLACK_WEBHOOK_URL_FAILED_2 }}
