name: Common Deployment Workflow

on:
  workflow_call:
    inputs:
      ENV_VAR:
        required: true
        type: string

jobs:

  github-variable-print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      # github variable 出力
      # github.ref: ワークフローがトリガーされたリファレンスまたはブランチ。プルリクエストの場合、この値はプルリクエストのマージブランチになります（例：refs/pull/:prNumber/merge）。
      # github.ref_name: ワークフローがトリガーされたリファレンスの名前。これはブランチ名またはタグ名になります。
      # github.head_ref: プルリクエストのソースブランチの名前。プルリクエスト以外のイベントではこの値は空です。
      # github.base_ref: プルリクエストのターゲットブランチの名前。プルリクエスト以外のイベントではこの値は空です。
      - name: Print github
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
          echo '6' ${{ github.event_name }}

  # 開発環境へのデプロイ
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Development ENV_VAR
        run: echo ${{ env.ENV_VAR }}
        # 開発環境へのデプロイスクリプトを記述

  # ステージング環境へのデプロイ
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Staging ENV_VAR
        run: echo ${{ inputs.ENV_VAR }}
        # ステージング環境へのデプロイスクリプトを記述

  # 本番環境へのデプロイ
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production ENV_VAR
        run: echo ${{ inputs.ENV_VAR }}
